version: '3'

services:

  httpd:
    image: php:5.6-apache
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./public_html:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini

  # Use root/root as user/password credentials
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081