version: '3'

services:

  apache:
    image: php:5.6-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini

  # Use root/root as user/password credentials
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080